### ISSUE TITLE
Set `update-major` to "breaking" by default?

### ISSUE THREAD

**Issue by pat-s** [thegeeklab/git-sv#117]
Wondering why the default is empty but at the same time there is a release-section that processes breaking changes by also hasn't any `commit-type` assigned?

**Comment by xoxys** [comment]
Breaking changes are detected by two mechanisms:

- `BREAKING CHANGE` string in commit message body
- commit subject with `!` suffix, e.g. `feat!`

Major version bumps are always performed if the history contains any breaking changes detected by one of the mechanisms described above. The `versioning.update-major` config option is intended to bump major versions on other commit types, e.g. `versioning.update-major: [refactor]` to bump the major version also on all refactor commits.

What you are asking for is a default configuration to tread commit messages like `breaking: this commit breaks everything` as a breaking change by default?

**Comment by pat-s** [comment]
Ah yes, my bad. Fully compliant with conv commits (sorry, never had to use a breaking commit so far since applying conv commits). Intuitively I thought about the `breaking:` prefix but I see that not having that prefix defined is more accurate.

> What you are asking for is a default configuration to tread commit messages like breaking: this commit breaks everything as a breaking change by default?

Yes but users can do so anyway in their config then. I guess sticking with conv commit defaults is the best approach.
